# Generated by Django 3.2 on 2022-12-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Cakes', 'Cakes'), ('Order', 'Order'), ('Account', 'Account'), ('Other', 'Other')], default='Cakes', max_length=20),
        ),
    ]
