# Generated by Django 3.2 on 2022-12-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221216_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customized_message',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
