# Generated by Django 3.2 on 2022-12-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221225_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_flavor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
